version: '3.7'
networks:
  kseed_net:
    name: kseed_net
    driver: bridge

services: 
  mysql:
    image: mysql
    build: ./requirements/mariadb
    volumes: 
      - mysql:/var/lib/mysql
    user: root
    env_file:
      - .env
    container_name: mysql
    expose: 
      - "3306"
    networks: 
      - kseed_net
    restart: unless-stopped
  wordpress:
    image: wordpress
    build: ./requirements/wordpress
    volumes: 
      - wordpress:/var/www/html
    env_file:
      - .env
    container_name: wordpress
    depends_on: 
      - mysql
    expose:
      - "9000"
      - "3306"
    networks: 
      - kseed_net
    restart: unless-stopped
  nginx:
    image: nginx
    build: ./requirements/nginx
    volumes: 
      - wordpress:/var/www/html
    ports:
      - 443:443
    container_name: nginx
    depends_on: 
      - wordpress
    networks: 
      - kseed_net
    restart: unless-stopped
     
volumes:
  wordpress:
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: /home/kseed/data/wp
  mysql:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/kseed/data/db
