version: '3.7'
networks:
  kseed_net:
    name: kseed_net
    driver: bridge

services: 
  mariadb:
    image: mariadb
    build: ./requirements/mariadb
    container_name: mariadb
    volumes: 
      - mysql:/var/lib/mysql
    user: root
    env_file: .env
    networks: 
      - kseed_net
    restart: unless-stopped

  wordpress:
    image: wordpress
    build: ./requirements/wordpress
    container_name: wordpress
    volumes: 
      - wordpress:/var/www/html
    env_file: .env
    depends_on: 
      - mariadb
    networks: 
      - kseed_net
    restart: unless-stopped

  nginx:
    image: nginx
    build: ./requirements/nginx
    container_name: nginx
    volumes: 
      - wordpress:/var/www/html
    ports:
      - "443:443"
    depends_on: 
      - wordpress
    networks: 
      - kseed_net
    restart: unless-stopped
     
volumes:
  wordpress:
    driver: local
    name: wp
    driver_opts: 
      type: none
      o: bind
      device: /home/kseed/data/wp
  mysql:
    driver: local
    name: db
    driver_opts:
      type: none
      o: bind
      device: /home/kseed/data/db
