version: '3.7'
networks:
  kseed_net:
    name: kseed_net
    driver: bridge

services: 
  mysql:
    image: mariadb
    build:
      context: ./srcs/mysql
      dockerfile: Dockerfile
    volumes: 
      - mysql:/var/lib/mysql
    env_file: .env
    container_name: mariadb
    expose: 
      - "3306"
    networks: 
      - kseed_net
  wordpress:
    image: wordpress
    build: 
      context: ./srcs/wordpress
      dockerfile: Dockerfile
    volumes: 
      - wordpress:/var/www/html
    env_file: .env
    container_name: wordpress
    depends_on: 
      - mariadb
    expose:
      - "9000"
    networks: 
      - kseed_net
  nginx:
    image: nginx
    build:
      context: ./srcs/nginx/
      dockerfile: Dockerfile
    volumes: 
      - wordpress:/var/www/html
    ports:
      - 443:443
    container_name: nginx
    depends_on: 
      - wordpress
    networks: 
      - kseed_net
     
volumes:
  wordpress:
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: /home/kseed/data/wp
  mysql:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/kseed/data/db
