version: '3.3'
networks:
  kseed_net:
    driver: bridge

services: 
  nginx:
    build:
      context: ./srcs/nginx/
      dockerfile: Dockerfile
    volumes: 
      - wordpress:/var/www/html
    ports:
      - 443:443
    container_name: nginx
  mysql:
    image: mariadb
    build:
      context: ./srcs/mysql
      dockerfile: Dockerfile
    volumes: 
      - mysql:/var/lib/mysql
    environment:
      - "DB_NAME=wordpress"
      - "DB_USER=kseed"
      - "DB_PASS=kseed"
      - "ROOT_PASS=kseed123"
    container_name: mariadb
    expose: 
      - "3306"
  wordpress:
    image: wordpress
    build: 
      context: ./srcs/wordpress
      dockerfile: Dockerfile
    volumes: 
      - wordpress:/var/www/html
    environment:
      - "DB_NAME=wordpress"
      - "DB_USER=kseed"
      - "DB_PASS=kseed"
      - "ROOT_PASS=kseed123"
    expose:
      - "9000"
     
volumes:
  wordpress:
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: /home/kseed/files/wp
  mysql:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/kseed/files/db